prediction on location 278671

In [21]:
import pandas as pd 
import numpy as np

In [22]:
df = pd.read_csv('CPCB/location_278671_merged.csv')
df.head()

,value,coordinates,summary,sensor_id,location_id,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,...,coverage.datetimeTo.utc,coverage.datetimeTo.local,date,site,AOD,T2M,RH2M,U2M,V2M,PS
0,0.40,NaN,NaN,12237012,278671,False,102,co,ppb,NaN,...,2025-02-18T20:15:00Z,2025-02-19T01:45:00+05:30,2025-02-18,location_278671,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
1,0.39,NaN,NaN,12237012,278671,False,102,co,ppb,NaN,...,2025-02-18T20:30:00Z,2025-02-19T02:00:00+05:30,2025-02-18,location_278671,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
2,0.40,NaN,NaN,12237012,278671,False,102,co,ppb,NaN,...,2025-02-18T20:45:00Z,2025-02-19T02:15:00+05:30,2025-02-18,location_278671,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
3,0.40,NaN,NaN,12237012,278671,False,102,co,ppb,NaN,...,2025-02-18T21:00:00Z,2025-02-19T02:30:00+05:30,2025-02-18,location_278671,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
4,0.41,NaN,NaN,12237012,278671,False,102,co,ppb,NaN,...,2025-02-18T21:15:00Z,2025-02-19T02:45:00+05:30,2025-02-18,location_278671,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99

In [23]:
df.drop(columns=['location_id', 'site'], inplace=True)
df.head()

,value,coordinates,summary,sensor_id,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,period.label,...,coverage.datetimeFrom.local,coverage.datetimeTo.utc,coverage.datetimeTo.local,date,AOD,T2M,RH2M,U2M,V2M,PS
0,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,2025-02-19T01:30:00+05:30,2025-02-18T20:15:00Z,2025-02-19T01:45:00+05:30,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
1,0.39,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,2025-02-19T01:45:00+05:30,2025-02-18T20:30:00Z,2025-02-19T02:00:00+05:30,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
2,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,2025-02-19T02:00:00+05:30,2025-02-18T20:45:00Z,2025-02-19T02:15:00+05:30,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
3,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,2025-02-19T02:15:00+05:30,2025-02-18T21:00:00Z,2025-02-19T02:30:00+05:30,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
4,0.41,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,2025-02-19T02:30:00+05:30,2025-02-18T21:15:00Z,2025-02-19T02:45:00+05:30,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99

In [24]:
df.describe()

,value,coordinates,summary,sensor_id,parameter.id,parameter.displayName,coverage.expectedCount,coverage.observedCount,coverage.percentComplete,coverage.percentCoverage,AOD,T2M,RH2M,U2M,V2M,PS
count,15000.000000,0.0,0.0,1.500000e+04,15000.000000,0.0,15000.0,15000.0,15000.0,15000.0,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,122.870764,NaN,NaN,7.976330e+06,31.133333,NaN,1.0,1.0,100.0,100.0,-184.909990,295.287634,42.224017,0.027163,0.060570,98943.122257
std,500.003426,NaN,NaN,5.218428e+06,42.093155,NaN,0.0,0.0,0.0,0.0,320.546245,1.431256,3.842712,0.755901,0.622461,264.000611
min,0.000000,NaN,NaN,1.585298e+06,1.000000,NaN,1.0,1.0,100.0,100.0,-999.000000,293.504180,37.642280,-1.377273,-1.240889,98521.180000
25%,7.030000,NaN,NaN,1.585301e+06,2.000000,NaN,1.0,1.0,100.0,100.0,-165.925280,294.020230,39.040077,-0.500017,-0.396695,98686.730000
50%,21.000000,NaN,NaN,1.223701e+07,5.000000,NaN,1.0,1.0,100.0,100.0,0.516530,294.951080,41.217022,0.190826,0.189992,98910.180000
75%,45.430000,NaN,NaN,1.223702e+07,98.000000,NaN,1.0,1.0,100.0,100.0,0.579149,297.006680,45.765057,0.529877,0.710095,99227.180000
max,10000.000000,NaN,NaN,1.223702e+07,102.000000,NaN,1.0,1.0,100.0,100.0,1.051891,297.989040,50.166843,1.240691,0.887248,99332.180000

In [25]:
# need to remove where AOD is absent
df = df[df['AOD'].isna() == False]
df.describe()

,value,coordinates,summary,sensor_id,parameter.id,parameter.displayName,coverage.expectedCount,coverage.observedCount,coverage.percentComplete,coverage.percentCoverage,AOD,T2M,RH2M,U2M,V2M,PS
count,9000.000000,0.0,0.0,9.000000e+03,9000.000000,0.0,9000.0,9000.0,9000.0,9000.0,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,21.076851,NaN,NaN,1.223702e+07,49.555556,NaN,1.0,1.0,100.0,100.0,-184.909990,295.287634,42.224017,0.027163,0.060570,98943.122257
std,20.099011,NaN,NaN,2.582132e+00,45.855237,NaN,0.0,0.0,0.0,0.0,320.546245,1.431256,3.842712,0.755901,0.622461,264.000611
min,0.150000,NaN,NaN,1.223701e+07,1.000000,NaN,1.0,1.0,100.0,100.0,-999.000000,293.504180,37.642280,-1.377273,-1.240889,98521.180000
25%,4.950000,NaN,NaN,1.223701e+07,3.000000,NaN,1.0,1.0,100.0,100.0,-165.925280,294.020230,39.040077,-0.500017,-0.396695,98686.730000
50%,17.110000,NaN,NaN,1.223702e+07,24.000000,NaN,1.0,1.0,100.0,100.0,0.516530,294.951080,41.217022,0.190826,0.189992,98910.180000
75%,28.080000,NaN,NaN,1.223702e+07,100.000000,NaN,1.0,1.0,100.0,100.0,0.579149,297.006680,45.765057,0.529877,0.710095,99227.180000
max,108.140000,NaN,NaN,1.223702e+07,102.000000,NaN,1.0,1.0,100.0,100.0,1.051891,297.989040,50.166843,1.240691,0.887248,99332.180000

In [26]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(df.iloc[:, 1:], df['value'], test_size=0.2)
print(X_train.head())
print(y_train.head())
print(X_train.shape, y_test.shape)

      coordinates  summary  sensor_id  flagInfo.hasFlags  parameter.id  \
1068          NaN      NaN   12237015              False             3
2935          NaN      NaN   12237019              False           101
4852          NaN      NaN   12237014              False            15
18            NaN      NaN   12237012              False           102
4323          NaN      NaN   12237014              False            15

     parameter.name parameter.units  parameter.displayName period.label  \
1068             o3           µg/m³                    NaN          raw
2935            so2             ppb                    NaN          raw
4852            no2             ppb                    NaN          raw
18               co             ppb                    NaN          raw
4323            no2             ppb                    NaN          raw

     period.interval  ... coverage.datetimeFrom.local coverage.datetimeTo.utc  \
1068        00:15:00  ...   2025-02-19T18:45:00+05:30    2025-02-19T13:30:00Z
2935        00:15:00  ...   2025-03-01T10:30:00+05:30    2025-03-01T05:15:00Z
4852        00:15:00  ...   2025-02-28T11:00:00+05:30    2025-02-28T05:45:00Z
18          00:15:00  ...   2025-02-19T06:00:00+05:30    2025-02-19T00:45:00Z
4323        00:15:00  ...   2025-02-22T14:15:00+05:30    2025-02-22T09:00:00Z

      coverage.datetimeTo.local        date         AOD        T2M       RH2M  \
1068  2025-02-19T19:00:00+05:30  2025-02-19    0.791573  294.95108  45.765057
2935  2025-03-01T10:45:00+05:30  2025-03-01 -832.168900  297.00668  44.338870
4852  2025-02-28T11:15:00+05:30  2025-02-28 -832.167050  297.98904  39.329754
18    2025-02-19T06:15:00+05:30  2025-02-19    0.791573  294.95108  45.765057
4323  2025-02-22T14:30:00+05:30  2025-02-22    0.517999  293.50418  39.304157

           U2M       V2M        PS
1068 -0.792893  0.189992  98686.73
2935  0.295931 -0.302023  98582.48
4852  1.178001  0.407594  98521.18
18   -0.792893  0.189992  98686.73
4323  1.240691 -1.240889  99068.01

[5 rows x 31 columns]
      coordinates  summary  sensor_id  flagInfo.hasFlags  parameter.id  \
3263          NaN      NaN   12237017              False             2
1252          NaN      NaN   12237015              False             3
8687          NaN      NaN   12237016              False             1
2602          NaN      NaN   12237019              False           101
1402          NaN      NaN   12237015              False             3

     parameter.name parameter.units  parameter.displayName period.label  \
3263           pm25           µg/m³                    NaN          raw
1252             o3           µg/m³                    NaN          raw
8687           pm10           µg/m³                    NaN          raw
2602            so2             ppb                    NaN          raw
1402             o3           µg/m³                    NaN          raw

     period.interval  ... coverage.datetimeFrom.local coverage.datetimeTo.utc  \
3263        00:15:00  ...   2025-02-21T22:00:00+05:30    2025-02-21T16:45:00Z
1252        00:15:00  ...   2025-02-21T19:15:00+05:30    2025-02-21T14:00:00Z
8687        00:15:00  ...   2025-02-26T14:15:00+05:30    2025-02-26T09:00:00Z
2602        00:15:00  ...   2025-02-25T15:45:00+05:30    2025-02-25T10:30:00Z
1402        00:15:00  ...   2025-02-23T11:15:00+05:30    2025-02-23T06:00:00Z

      coverage.datetimeTo.local        date         AOD        T2M       RH2M  \
3263  2025-02-21T22:15:00+05:30  2025-02-21    0.516530  295.11600  46.622020
1252  2025-02-21T19:30:00+05:30  2025-02-21    0.516530  295.11600  46.622020
8687  2025-02-26T14:30:00+05:30  2025-02-26 -165.882000  296.13430  37.642280
2602  2025-02-25T16:00:00+05:30  2025-02-25    1.051891  293.81015  41.217022
1402  2025-02-23T11:30:00+05:30  2025-02-23    0.558187  294.02023  42.627003

           U2M       V2M         PS
3263  0.529877 -0.396695  98910.180
1252  0.529877 -0.396695  98910.180
8687 -0.500017  0.710095  99227.180
2602 -0.130930  0.418930  99332.180
1402  0.194208 -0.431731  99131.945

[5 rows x 31 columns]
(7200, 31) (1800,)

In [27]:
cnt = 0
chodo = ['coverage.expectedCount', 'coverage.expectedInterval', 'coverage.observedCount', 'coverage.observedInterval', 'coverage.percentComplete', 'coverage.percentCoverage']
for column in df.columns:
    if column.startswith('coverage.'):
        if column in chodo: continue
        df.drop(columns=[column], inplace=True)
        print(f'Dropped {column}')
        cnt += 1
print(f'Dropped {cnt} columns')
df.describe()

Dropped coverage.datetimeFrom.utc
Dropped coverage.datetimeFrom.local
Dropped coverage.datetimeTo.utc
Dropped coverage.datetimeTo.local
Dropped 4 columns

,value,coordinates,summary,sensor_id,parameter.id,parameter.displayName,coverage.expectedCount,coverage.observedCount,coverage.percentComplete,coverage.percentCoverage,AOD,T2M,RH2M,U2M,V2M,PS
count,9000.000000,0.0,0.0,9.000000e+03,9000.000000,0.0,9000.0,9000.0,9000.0,9000.0,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,21.076851,NaN,NaN,1.223702e+07,49.555556,NaN,1.0,1.0,100.0,100.0,-184.909990,295.287634,42.224017,0.027163,0.060570,98943.122257
std,20.099011,NaN,NaN,2.582132e+00,45.855237,NaN,0.0,0.0,0.0,0.0,320.546245,1.431256,3.842712,0.755901,0.622461,264.000611
min,0.150000,NaN,NaN,1.223701e+07,1.000000,NaN,1.0,1.0,100.0,100.0,-999.000000,293.504180,37.642280,-1.377273,-1.240889,98521.180000
25%,4.950000,NaN,NaN,1.223701e+07,3.000000,NaN,1.0,1.0,100.0,100.0,-165.925280,294.020230,39.040077,-0.500017,-0.396695,98686.730000
50%,17.110000,NaN,NaN,1.223702e+07,24.000000,NaN,1.0,1.0,100.0,100.0,0.516530,294.951080,41.217022,0.190826,0.189992,98910.180000
75%,28.080000,NaN,NaN,1.223702e+07,100.000000,NaN,1.0,1.0,100.0,100.0,0.579149,297.006680,45.765057,0.529877,0.710095,99227.180000
max,108.140000,NaN,NaN,1.223702e+07,102.000000,NaN,1.0,1.0,100.0,100.0,1.051891,297.989040,50.166843,1.240691,0.887248,99332.180000

In [28]:
for column in chodo:
    # print 5 values from that column
    print(df[column].head())

0    1
1    1
2    1
3    1
4    1
Name: coverage.expectedCount, dtype: int64
0    00:15:00
1    00:15:00
2    00:15:00
3    00:15:00
4    00:15:00
Name: coverage.expectedInterval, dtype: object
0    1
1    1
2    1
3    1
4    1
Name: coverage.observedCount, dtype: int64
0    00:15:00
1    00:15:00
2    00:15:00
3    00:15:00
4    00:15:00
Name: coverage.observedInterval, dtype: object
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
Name: coverage.percentComplete, dtype: float64
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
Name: coverage.percentCoverage, dtype: float64

# now the thing is that in the data there is a column named parameter.name and what i want is for each parameter name there should be a new column and just maintain a small list of mapping from parameter.name to parameter.units for only unique parameter.name values

In [29]:
# Propagate met / AOD variables from the SO2 row (or any row that has them)
# to all other parameter.name rows sharing the same period.datetimeFrom.utc timestamp.

# List your met + AOD columns (correcting V3M -> V2M if needed)
met_cols = ['AOD', 'T2M', 'RH2M', 'U2M', 'V2M', 'PS']
missing_in_df = [c for c in met_cols if c not in df.columns]
if missing_in_df:
    print("Warning: columns not found, skipping:", missing_in_df)
    met_cols = [c for c in met_cols if c in df.columns]

time_col = 'period.datetimeFrom.utc'

# Build per-timestamp table taking the first non-null value for each column
per_time = (
    df.groupby(time_col, dropna=False)[met_cols]
      .agg(lambda s: s.dropna().iloc[0] if s.notna().any() else np.nan)
)

# Merge back (suffix _fill for the aggregated values)
df = df.merge(per_time, left_on=time_col, right_index=True, suffixes=('', '_fill'))

# For each met col: keep original if present else use the filled value
for c in met_cols:
    fill_col = c + '_fill'
    df[c] = df[c].where(df[c].notna(), df[fill_col])
    df.drop(columns=[fill_col], inplace=True)

# (Optional) verify no remaining NaNs where at least one row had data
check = df.groupby(time_col)[met_cols].apply(lambda g: g.isna().all()).any()
print("Any timestamps with all-NaN met cols?", check)

df.head()

Any timestamps with all-NaN met cols? AOD     False
T2M     False
RH2M    False
U2M     False
V2M     False
PS      False
dtype: bool

,value,coordinates,summary,sensor_id,flagInfo.hasFlags,parameter.id,parameter.name,parameter.units,parameter.displayName,period.label,...,coverage.observedInterval,coverage.percentComplete,coverage.percentCoverage,date,AOD,T2M,RH2M,U2M,V2M,PS
0,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,00:15:00,100.0,100.0,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
1,0.39,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,00:15:00,100.0,100.0,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
2,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,00:15:00,100.0,100.0,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
3,0.40,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,00:15:00,100.0,100.0,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99
4,0.41,NaN,NaN,12237012,False,102,co,ppb,NaN,raw,...,00:15:00,100.0,100.0,2025-02-18,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99

In [30]:
# save df as csv
df.to_csv('tst.csv', index=False)

In [31]:
# Create wide columns for each parameter.name and a mapping to parameter.units

# 1. Build mapping (parameter.name -> parameter.units)
param_unit_map = (
    df[['parameter.name', 'parameter.units']]
    .drop_duplicates()
    .groupby('parameter.name')['parameter.units']
    .first()
    .to_dict()
)
print("Parameter -> Units mapping:")
for k, v in param_unit_map.items():
    print(f"{k}: {v}")

# 2. Pivot value column so each parameter.name becomes its own column
#    Use period.datetimeTo.utc as the time key (fallback to From if missing)
_time_col = 'period.datetimeTo.utc'
if _time_col not in df or df[_time_col].isna().all():
    _time_col = 'period.datetimeFrom.utc'

# Ensure datetime type (optional)
df['_ts'] = pd.to_datetime(df[_time_col], errors='coerce')

wide_df = (
    df.pivot_table(
        index=['_ts'],              # you can add other id cols if needed
        columns='parameter.name',
        values='value',
        aggfunc='mean'              # if multiple rows per ts+parameter
    )
    .reset_index()
)

# 3. (Optional) add a pure date column
wide_df['date'] = wide_df['_ts'].dt.date

# 4. (Optional) merge back any non-parameter features you still need (drop dup rows first)
#    Example: keep AOD and met variables if they are aligned by timestamp
cols_keep = [c for c in df.columns if c not in ['value', 'parameter.name', 'parameter.units']]
base = df.drop_duplicates(subset=['_ts'])[cols_keep]
final_df = pd.merge(base, wide_df, on='_ts', how='left')

# 5. Drop helper column if not needed
final_df.drop(columns=['_ts'], inplace=True)

# final_df now has one column per parameter.name plus original metadata
print(final_df.head())

Parameter -> Units mapping:
co: ppb
no: ppb
no2: ppb
o3: µg/m³
pm10: µg/m³
pm25: µg/m³
relativehumidity: %
so2: ppb
temperature: c
   coordinates  summary  sensor_id  flagInfo.hasFlags  parameter.id  \
0          NaN      NaN   12237012              False           102
1          NaN      NaN   12237012              False           102
2          NaN      NaN   12237012              False           102
3          NaN      NaN   12237012              False           102
4          NaN      NaN   12237012              False           102

   parameter.displayName period.label period.interval period.datetimeFrom.utc  \
0                    NaN          raw        00:15:00    2025-02-18T20:00:00Z
1                    NaN          raw        00:15:00    2025-02-18T20:15:00Z
2                    NaN          raw        00:15:00    2025-02-18T20:30:00Z
3                    NaN          raw        00:15:00    2025-02-18T20:45:00Z
4                    NaN          raw        00:15:00    2025-02-18T21:00:00Z

   period.datetimeFrom.local  ...    co     no   no2    o3   pm10   pm25  \
0  2025-02-19T01:30:00+05:30  ...  0.40  11.50  5.23  0.56  43.87  27.42
1  2025-02-19T01:45:00+05:30  ...  0.39  11.21  4.91  0.49  42.90  26.81
2  2025-02-19T02:00:00+05:30  ...  0.40  11.46  4.95  0.52  42.53  26.58
3  2025-02-19T02:15:00+05:30  ...  0.40  11.56  4.93  0.49  42.53  26.58
4  2025-02-19T02:30:00+05:30  ...  0.41  11.58  5.17  0.27  42.53  26.58

   relativehumidity    so2 temperature      date_y
0             88.94  25.06       16.29  2025-02-18
1             88.89  25.22       16.23  2025-02-18
2             88.91  25.40       16.10  2025-02-18
3             88.94  25.97       16.09  2025-02-18
4             88.99  26.16       16.05  2025-02-18

[5 rows x 35 columns]

In [32]:
final_df.to_csv('with_all.csv', index=False)

this is the point where i think data is clean and now i can start EDA and feature engineering

In [33]:
from ydata_profiling import ProfileReport
import os
if not os.path.exists("final_report.html"):
    pf = ProfileReport(final_df)
    pf.to_file("final_report.html")

In [34]:
# now i want to know what all features that can be really impactful in PM prediction
# but first i want to know what all features are available in the dataset
for column in final_df.columns:
    print(column)

coordinates
summary
sensor_id
flagInfo.hasFlags
parameter.id
parameter.displayName
period.label
period.interval
period.datetimeFrom.utc
period.datetimeFrom.local
period.datetimeTo.utc
period.datetimeTo.local
coverage.expectedCount
coverage.expectedInterval
coverage.observedCount
coverage.observedInterval
coverage.percentComplete
coverage.percentCoverage
date_x
AOD
T2M
RH2M
U2M
V2M
PS
co
no
no2
o3
pm10
pm25
relativehumidity
so2
temperature
date_y

summary, sensor_id, flagInfo.hasFlags, parameter.id, parameter.displayName, period.label, period.datetimeFrom.utc, period.datetimeFrom.local, period.datetimeTo.utc, period.datetimeTo.local, coverage.expectedCount, coverage.expectedInterval, coverage.observedCount, coverage.observedInterval, coverage.percentComplete, coverage.percentCoverage, (one of date_x/date_y as it is duplicate and rename as date)

In [35]:
print(final_df['date_x'].head())
print(final_df['date_y'].head())

0    2025-02-18
1    2025-02-18
2    2025-02-18
3    2025-02-18
4    2025-02-18
Name: date_x, dtype: object
0    2025-02-18
1    2025-02-18
2    2025-02-18
3    2025-02-18
4    2025-02-18
Name: date_y, dtype: object

In [36]:
# Drop unwanted metadata columns and unify date_x/date_y -> date

cols_to_drop = [
    "summary","sensor_id","flagInfo.hasFlags","parameter.id","parameter.displayName",
    "period.label","period.datetimeFrom.utc","period.datetimeFrom.local",
    "period.datetimeTo.utc","period.datetimeTo.local",
    "coverage.expectedCount","coverage.expectedInterval","coverage.observedCount",
    "coverage.observedInterval","coverage.percentComplete","coverage.percentCoverage"
]

# Handle duplicate date columns
if "date_x" in final_df.columns and "date_y" in final_df.columns:
    # If they differ, keep the non-null or first; warn if mismatch
    if not final_df["date_x"].equals(final_df["date_y"]):
        print("Warning: date_x and date_y differ in some rows; taking first non-null.")
    final_df["date"] = final_df["date_x"].where(final_df["date_x"].notna(), final_df["date_y"])
    cols_to_drop.extend(["date_x","date_y"])
elif "date_x" in final_df.columns:
    final_df.rename(columns={"date_x":"date"}, inplace=True)
    cols_to_drop.append("date_x")
elif "date_y" in final_df.columns:
    final_df.rename(columns={"date_y":"date"}, inplace=True)
    cols_to_drop.append("date_y")

# Drop only those that exist
final_df.drop(columns=[c for c in cols_to_drop if c in final_df.columns], inplace=True, errors="ignore")

Warning: date_x and date_y differ in some rows; taking first non-null.

In [37]:
final_df.head()

,coordinates,period.interval,AOD,T2M,RH2M,U2M,V2M,PS,co,no,no2,o3,pm10,pm25,relativehumidity,so2,temperature,date
0,NaN,00:15:00,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99,0.40,11.50,5.23,0.56,43.87,27.42,88.94,25.06,16.29,2025-02-18
1,NaN,00:15:00,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99,0.39,11.21,4.91,0.49,42.90,26.81,88.89,25.22,16.23,2025-02-18
2,NaN,00:15:00,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99,0.40,11.46,4.95,0.52,42.53,26.58,88.91,25.40,16.10,2025-02-18
3,NaN,00:15:00,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99,0.40,11.56,4.93,0.49,42.53,26.58,88.94,25.97,16.09,2025-02-18
4,NaN,00:15:00,-999.0,295.38037,42.619175,-0.474309,0.278926,98800.99,0.41,11.58,5.17,0.27,42.53,26.58,88.99,26.16,16.05,2025-02-18

In [38]:
final_df.drop(columns=['coordinates', 'period.interval'], inplace=True, errors="ignore")

domain specific feature engineering

meteorological features

In [42]:
final_df['wind_speed'] = np.sqrt(final_df['U2M']**2 + final_df['V2M']**2)
final_df.drop(columns=['U2M', 'V2M'], inplace = True)

In [43]:
final_df['THI'] = final_df['T2M'] - (0.55 - 0.0055 * final_df['RH2M']) * (final_df['T2M'] - 14.5)
final_df.drop(columns=['T2M', 'RH2M'], inplace = True)

In [44]:
# Compute pollution interaction ratios
# Assumes columns are named as lowercase: 'co', 'no', 'no2', 'o3', 'pm10', 'pm25', 'relativehumidity', 'so2'

def safe_div(num, den):
    return np.where((den == 0) | (den.isna()), np.nan, num / den)

# NO₂ / NO (Oxidation indicator)
if 'no2' in final_df.columns and 'no' in final_df.columns:
    final_df['no2_no_ratio'] = safe_div(final_df['no2'], final_df['no'])

# NOx / NO₂ or (NO + NO₂)/NO₂ (Photochemical balance)
if 'no' in final_df.columns and 'no2' in final_df.columns:
    final_df['nox_no2_ratio'] = safe_div(final_df['no'] + final_df['no2'], final_df['no2'])

# O₃ / NOx (Ozone production indicator)
if 'o3' in final_df.columns and 'no' in final_df.columns and 'no2' in final_df.columns:
    final_df['o3_nox_ratio'] = safe_div(final_df['o3'], final_df['no'] + final_df['no2'])

# CO / NOx (Combustion efficiency)
if 'co' in final_df.columns and 'no' in final_df.columns and 'no2' in final_df.columns:
    final_df['co_nox_ratio'] = safe_div(final_df['co'], final_df['no'] + final_df['no2'])

# SO₂ / NO₂ (Industrial vs. vehicular source split)
if 'so2' in final_df.columns and 'no2' in final_df.columns:
    final_df['so2_no2_ratio'] = safe_div(final_df['so2'], final_df['no2'])

# Drop individual gas columns (keep only ratios and PM/relativehumidity)
drop_cols = ['co', 'no', 'no2', 'o3', 'so2']
final_df.drop(columns=[c for c in drop_cols if c in final_df.columns], inplace=True)

print(final_df.head())

     AOD        PS   pm10   pm25  relativehumidity  temperature        date  \
0 -999.0  98800.99  43.87  27.42             88.94        16.29  2025-02-18
1 -999.0  98800.99  42.90  26.81             88.89        16.23  2025-02-18
2 -999.0  98800.99  42.53  26.58             88.91        16.10  2025-02-18
3 -999.0  98800.99  42.53  26.58             88.94        16.09  2025-02-18
4 -999.0  98800.99  42.53  26.58             88.99        16.05  2025-02-18

   no2_no_ratio  nox_no2_ratio  o3_nox_ratio  co_nox_ratio  so2_no2_ratio  \
0      0.454783       3.198853      0.033473      0.023909       4.791587
1      0.438002       3.283096      0.030397      0.024194       5.136456
2      0.431937       3.315152      0.031688      0.024375       5.131313
3      0.426471       3.344828      0.029715      0.024257       5.267748
4      0.446459       3.239845      0.016119      0.024478       5.059961

   wind_speed        THI
0    0.550244  206.73606
1    0.550244  206.73606
2    0.550244  206.73606
3    0.550244  206.73606
4    0.550244  206.73606

now i think i should apply ML models on this Final DF

In [45]:
final_df.to_csv('final_features.csv', index=False)

In [46]:
# === PM10 / PM25 Prediction with XGBoost + Stacking Ensemble ===
# Requirements: scikit-learn, xgboost. Install if needed:
# %pip install xgboost

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, StackingRegressor
from sklearn.linear_model import Ridge
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor

# Ensure final_df exists (if loaded from CSV)
# final_df = pd.read_csv("final_features.csv")

# Helper: numeric feature matrix
def prep_features(df, target, drop_other_pm=False):
    df = final_df.copy()
    # Identify PM columns present
    pm_cols = [c for c in df.columns if c.lower() in ("pm25","pm2.5","pm10")]
    # Normalize pm2.5 naming if needed
    if "pm2.5" in df.columns and "pm25" not in df.columns:
        df.rename(columns={"pm2.5":"pm25"}, inplace=True)

    # Drop rows with missing target
    df = df[df[target].notna()]
    # Optionally drop the other PM column
    if drop_other_pm:
        for c in pm_cols:
            if c != target and c in df.columns:
                df.drop(columns=[c], inplace=True, errors="ignore")

    # Remove target from feature set after copying
    y = df[target].values

    # Drop obvious non-predictive / identifier / date-like text columns
    drop_like = ["date","timestamp"]
    for d in drop_like:
        if d in df.columns:
            df.drop(columns=[d], inplace=True)

    # Keep only numeric
    X = df.drop(columns=[target], errors="ignore")
    numeric_cols = X.select_dtypes(include=[np.number, "float64","float32","int64"]).columns.tolist()
    X = X[numeric_cols]

    return X, y, numeric_cols

def evaluate(model, X_train, X_test, y_train, y_test, label):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    rmse = mean_squared_error(y_test, pred, squared=False)
    mae = mean_absolute_error(y_test, pred)
    r2 = r2_score(y_test, pred)
    print(f"{label} -> RMSE: {rmse:.3f}  MAE: {mae:.3f}  R2: {r2:.3f}")
    return {"model":model,"pred":pred,"rmse":rmse,"mae":mae,"r2":r2}

def build_models(random_state=42):
    xgb = XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        objective="reg:squarederror",
        random_state=random_state,
        n_jobs=-1
    )
    rf = RandomForestRegressor(
        n_estimators=300,
        max_depth=None,
        min_samples_split=4,
        n_jobs=-1,
        random_state=random_state
    )
    gbr = GradientBoostingRegressor(random_state=random_state)
    stack = StackingRegressor(
        estimators=[
            ("xgb", xgb),
            ("rf", rf),
            ("gbr", gbr)
        ],
        final_estimator=Ridge(alpha=1.0),
        n_jobs=-1,
        passthrough=False
    )
    return xgb, stack

def run_case(target, drop_other_pm):
    print(f"\n=== Target: {target} | Drop other PM: {drop_other_pm} ===")
    X, y, feats = prep_features(final_df, target=target, drop_other_pm=drop_other_pm)

    # Train / test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Pipeline (impute + scale (for linear/blend stability) + model)
    xgb, stack = build_models()

    base_pipe = Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("model", xgb)
    ])
    stack_pipe = Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler(with_mean=False)),  # sparse-safe
        ("model", stack)
    ])

    # Cross-validation (optional)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    cv_rmse_xgb = -cross_val_score(
        base_pipe, X, y, scoring="neg_root_mean_squared_error", cv=kf, n_jobs=-1
    ).mean()
    cv_rmse_stack = -cross_val_score(
        stack_pipe, X, y, scoring="neg_root_mean_squared_error", cv=kf, n_jobs=-1
    ).mean()
    print(f"CV RMSE (XGB): {cv_rmse_xgb:.3f} | CV RMSE (Stack): {cv_rmse_stack:.3f}")

    results = {}
    results["xgb"] = evaluate(base_pipe, X_train, X_test, y_train, y_test, "XGBoost Test")
    results["stack"] = evaluate(stack_pipe, X_train, X_test, y_train, y_test, "Stacking Test")

    # Feature importance (XGB only)
    base_pipe.fit(X_train, y_train)
    try:
        importances = base_pipe.named_steps["model"].feature_importances_
        fi = pd.Series(importances, index=X.columns).sort_values(ascending=False).head(20)
        print("\nTop 20 XGB feature importances:")
        print(fi)
    except Exception as e:
        print("Could not extract feature importances:", e)

    return results

# Run all four scenarios
# 1. Predict pm25 with all columns
if "pm25" in final_df.columns:
    res_pm25_all = run_case("pm25", drop_other_pm=False)
    # 2. Predict pm25 without pm10
    if "pm10" in final_df.columns:
        res_pm25_no_pm10 = run_case("pm25", drop_other_pm=True)

# 3. Predict pm10 with all columns
if "pm10" in final_df.columns:
    res_pm10_all = run_case("pm10", drop_other_pm=False)
    # 4. Predict pm10 without pm25
    if "pm25" in final_df.columns:
        res_pm10_no_pm25 = run_case("pm10", drop_other_pm=True)

# (Optional) Save results summary
summary = []
for name, res in [
    ("pm25_all", locals().get("res_pm25_all")),
    ("pm25_no_pm10", locals().get("res_pm25_no_pm10")),
    ("pm10_all", locals().get("res_pm10_all")),
    ("pm10_no_pm25", locals().get("res_pm10_no_pm25"))
]:
    if res:
        for model_name, metrics in res.items():
            summary.append({
                "scenario": name,
                "model": model_name,
                "RMSE": metrics["rmse"],
                "MAE": metrics["mae"],
                "R2": metrics["r2"]
            })

if summary:
    summary_df = pd.DataFrame(summary)
    print("\n=== Summary ===")
    print(summary_df)

=== Target: pm25 | Drop other PM: False ===
CV RMSE (XGB): 0.511 | CV RMSE (Stack): 0.721

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

XGBoost Test -> RMSE: 1.074  MAE: 0.277  R2: 0.989

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Stacking Test -> RMSE: 0.653  MAE: 0.119  R2: 0.996

Top 20 XGB feature importances:
pm10                0.792246
co_nox_ratio        0.108987
THI                 0.047133
temperature         0.012012
wind_speed          0.010771
AOD                 0.010442
relativehumidity    0.007622
PS                  0.005656
o3_nox_ratio        0.003838
no2_no_ratio        0.000873
nox_no2_ratio       0.000234
so2_no2_ratio       0.000185
dtype: float32

=== Target: pm25 | Drop other PM: True ===
CV RMSE (XGB): 2.731 | CV RMSE (Stack): 3.146

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

XGBoost Test -> RMSE: 2.631  MAE: 1.820  R2: 0.934

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Stacking Test -> RMSE: 2.716  MAE: 1.834  R2: 0.930

Top 20 XGB feature importances:
co_nox_ratio        0.405298
THI                 0.187000
PS                  0.110207
wind_speed          0.063859
o3_nox_ratio        0.063781
relativehumidity    0.051189
temperature         0.044386
AOD                 0.037450
so2_no2_ratio       0.015992
no2_no_ratio        0.011536
nox_no2_ratio       0.009302
dtype: float32

=== Target: pm10 | Drop other PM: False ===
CV RMSE (XGB): 0.817 | CV RMSE (Stack): 0.974

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

XGBoost Test -> RMSE: 1.714  MAE: 0.450  R2: 0.989

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Stacking Test -> RMSE: 0.706  MAE: 0.156  R2: 0.998

Top 20 XGB feature importances:
pm25                0.789893
co_nox_ratio        0.113641
THI                 0.046558
temperature         0.010852
wind_speed          0.010847
AOD                 0.010082
relativehumidity    0.007907
PS                  0.004931
o3_nox_ratio        0.003854
no2_no_ratio        0.001014
nox_no2_ratio       0.000241
so2_no2_ratio       0.000179
dtype: float32

=== Target: pm10 | Drop other PM: True ===
CV RMSE (XGB): 4.355 | CV RMSE (Stack): 5.012

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

XGBoost Test -> RMSE: 4.154  MAE: 2.890  R2: 0.936

c:\Users\lenovo\anaconda3\envs\ai-gpu\lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

Stacking Test -> RMSE: 4.266  MAE: 2.907  R2: 0.932

Top 20 XGB feature importances:
co_nox_ratio        0.417665
THI                 0.176685
PS                  0.106258
o3_nox_ratio        0.065832
wind_speed          0.062520
relativehumidity    0.052387
temperature         0.044268
AOD                 0.038106
so2_no2_ratio       0.015978
no2_no_ratio        0.011378
nox_no2_ratio       0.008922
dtype: float32

=== Summary ===
       scenario  model      RMSE       MAE        R2
0      pm25_all    xgb  1.074414  0.276632  0.989028
1      pm25_all  stack  0.652506  0.119464  0.995953
2  pm25_no_pm10    xgb  2.631182  1.819682  0.934195
3  pm25_no_pm10  stack  2.715686  1.833774  0.929901
4      pm10_all    xgb  1.713707  0.450248  0.989100
5      pm10_all  stack  0.705835  0.155890  0.998151
6  pm10_no_pm25    xgb  4.154267  2.889958  0.935945
7  pm10_no_pm25  stack  4.266475  2.907162  0.932438

In [47]:
summary_df.to_csv('model_comparison_summary.csv', index=False)